Add viper to hot reload configmap
elisasre/namespace-controller pull request #61
Opened 2023-01-30 14:20 UTC by vamaki

https://atlas.elisa.fi/jira/browse/DEV-3826

2023-02-06 07:52 UTC, zetaab commented on pkg/controller/handle.go
> +	if err := v.UnmarshalKey("adminnamespaces", &config.AdminNamespaces); err != nil {
eikö tyylikkäämpi ois vaan vetästä 

```
	if err := v.Unmarshal(&config); err != nil {
```

sillon ei tarvis kun yhden unmarshalin tässä ja onconfigchange sisällä

2023-02-06 08:01 UTC, zetaab requested changes

2023-02-06 08:01 UTC, zetaab commented on pkg/controller/handle.go
> +	log.Println("config file used: ", v.ConfigFileUsed())
`log.Printf("config file used: %s", v.ConfigFileUsed())`

2023-02-06 08:01 UTC, zetaab commented on pkg/controller/handle.go
> +		log.Println("Config file changed:", e.Name)
`log.Printf("Config file changed: %s", e.Name)`

2023-02-06 08:01 UTC, zetaab commented on pkg/controller/handle.go
> +		v.UnmarshalKey("adminnamespaces", &config.AdminNamespaces)
`if err := v.Unmarshal(&config); err != nil {` ja jos virhe tapahtuu niin vois vaikka laittaa `log.Fatalf("invalid config: %v", err)`

2023-02-06 12:45 UTC, vamaki commented on pkg/controller/handle.go
> +func makeConfig(c *Controller, path string) (*Config, error) {
Tän vois poistaa kokonaan, testit pitää muokata sen mukaan.

2023-02-28 11:04 UTC, zetaab commented
needs rebase

2023-03-15 06:07 UTC, merged

2023-03-15 06:08 UTC, zetaab commented
@vamaki tee peeärrä batchiin nostaakseen namespace-controllerin imagea uudempaan (näkee github actions logeista tästä reposta sen uuden imagen koordinaatit). Sitku batchista mergetty niin tän vois vielä verifioida jossain clusterissa